"""Schema setup, evolution and verification for the opt-in Postgres store.

`Base.metadata.create_all` (what `ensure_schema` used to be, on its own)
creates *missing tables* and nothing else: it never adds a column to a
table that already exists, never drops a constraint, and leaves no record
of what a given database actually has. So a deployment that ran `arp db
init-postgres` months ago had no way to tell whether its schema matched
today's models, and found out via `UndefinedColumn` at query time. The
SQLite side had already hit this and solved it by hand, once, for one
column (`document_registry.ensure_storage_uri_column`).

This module generalizes that, deliberately without adding Alembic. Three
pieces, in the order `ensure_schema` runs them:

1. **create_all** -- new tables, unchanged behaviour.
2. **additive column reconciliation** -- for every table the models
   define, `ALTER TABLE ... ADD COLUMN` for each column the database is
   missing. This is what `ensure_storage_uri_column` did, driven off the
   models instead of a hand-written list, and it covers the overwhelmingly
   common kind of change (a new nullable/defaulted column).
3. **explicit steps** (`SCHEMA_STEPS`) -- anything reconciliation can't
   infer: dropping a constraint, backfilling, renaming. Each runs once
   per database and is recorded in `schema_migrations`, so a database
   carries a record of what has been applied. Each is also written to be
   safe if re-run.

What is deliberately *not* attempted: dropping a column or table the
models no longer define, and changing a column's type or nullability.
Those are destructive or table-rewriting, so `schema_report` reports them
as drift for an operator to resolve rather than acting on its own. That
report is what `arp db check-postgres` prints, which is the "is this
database current?" answer that didn't exist before.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING

from arp.storage.postgres import PostgresExtraNotInstalled, get_engine

if TYPE_CHECKING:
    from sqlalchemy import Connection

_MIGRATIONS_TABLE = "schema_migrations"


@dataclass(frozen=True)
class SchemaStep:
    """One recorded, run-once schema change. `apply` must be safe to call
    against a database that already satisfies it: a step is recorded only
    after it succeeds, so a crash between the DDL and the record means the
    next run calls it again."""

    name: str
    description: str
    apply: Callable[[Connection], None]


def _drop_projection_company_fks(conn: Connection) -> None:
    """Drops the `company_id -> companies.company_id` foreign keys the
    projection tables used to carry.

    They made those three projections silently insert nothing: the
    `companies` table is only populated by the dual-write portfolio store
    (so, only under ARP_PORTFOLIO_BACKEND=postgres), while the companies a
    run reports on come from the user-supplied universe file -- and the
    projections' sync hooks are best-effort, so every insert failed the
    constraint and every failure was swallowed into a log line. See the
    module docstring in postgres_models.py for the full rule.

    Finds constraints by catalog lookup rather than by name: the names
    were generated by `create_all` and a database created by an older
    SQLAlchemy may spell them differently.
    """
    from sqlalchemy import text

    rows = conn.execute(
        text(
            """
            SELECT con.conrelid::regclass::text AS table_name, con.conname AS constraint_name
            FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_class parent ON parent.oid = con.confrelid
            WHERE con.contype = 'f'
              AND parent.relname = 'companies'
              AND child.relname IN ('company_records', 'company_facts', 'engagement_issues')
            """
        )
    ).all()
    for table_name, constraint_name in rows:
        conn.execute(text(f'ALTER TABLE {table_name} DROP CONSTRAINT "{constraint_name}"'))


# Ordered; append new steps, never edit or reorder an existing one (a
# database that already recorded it will not run it again).
SCHEMA_STEPS: tuple[SchemaStep, ...] = (
    SchemaStep(
        name="0001_drop_projection_company_fks",
        description="Drop company_records/company_facts/engagement_issues -> companies foreign keys",
        apply=_drop_projection_company_fks,
    ),
)


def _sqlalchemy():
    try:
        import sqlalchemy
    except ImportError as exc:  # pragma: no cover - exercised only without the optional extra
        raise PostgresExtraNotInstalled(exc) from exc
    return sqlalchemy


def _ensure_migrations_table(conn: Connection) -> None:
    from sqlalchemy import text

    conn.execute(
        text(
            f"CREATE TABLE IF NOT EXISTS {_MIGRATIONS_TABLE} ("
            " name TEXT PRIMARY KEY,"
            " applied_at TIMESTAMPTZ NOT NULL DEFAULT now()"
            ")"
        )
    )


def _applied_step_names(conn: Connection) -> set[str]:
    from sqlalchemy import text

    _ensure_migrations_table(conn)
    return {row[0] for row in conn.execute(text(f"SELECT name FROM {_MIGRATIONS_TABLE}")).all()}


def _missing_columns(conn: Connection) -> list[tuple[str, str]]:
    """(table, column) pairs the models define and the database lacks,
    for tables that already exist."""
    from sqlalchemy import inspect

    from arp.storage.postgres_models import Base

    inspector = inspect(conn)
    existing_tables = set(inspector.get_table_names())
    missing: list[tuple[str, str]] = []
    for table in Base.metadata.sorted_tables:
        if table.name not in existing_tables:
            continue  # create_all's job, not ours
        have = {col["name"] for col in inspector.get_columns(table.name)}
        missing.extend((table.name, column.name) for column in table.columns if column.name not in have)
    return missing


def _add_missing_columns(conn: Connection) -> list[tuple[str, str]]:
    from sqlalchemy import text

    from arp.storage.postgres_models import Base

    added = []
    for table_name, column_name in _missing_columns(conn):
        table = Base.metadata.tables[table_name]
        column = table.columns[column_name]
        ddl_type = column.type.compile(dialect=conn.dialect)
        # Added nullable regardless of the model's nullability: existing
        # rows have no value for it, so NOT NULL without a default would
        # fail outright. Tightening it afterwards is a data decision, and
        # schema_report flags the difference.
        conn.execute(text(f'ALTER TABLE {table_name} ADD COLUMN "{column_name}" {ddl_type}'))
        added.append((table_name, column_name))
    return added


def ensure_schema(dsn: str) -> dict:
    """Brings a database up to what the models define, idempotently: the
    pgvector extension, any missing tables, any missing columns, then any
    unapplied step from SCHEMA_STEPS. Safe to run against a fresh
    database, one created before this module existed, or one that is
    already current (then it changes nothing). Call it from `arp db
    init-postgres`, not per request.

    Returns what it did -- `{"tables_created": [...], "columns_added":
    [...], "steps_applied": [...]}` -- so the CLI can report it instead of
    claiming success without detail.
    """
    sqlalchemy = _sqlalchemy()
    from sqlalchemy import inspect, text

    from arp.storage.postgres_models import Base

    engine = get_engine(dsn)
    with engine.begin() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))

    with engine.connect() as conn:
        before = set(inspect(conn).get_table_names())

    Base.metadata.create_all(engine)

    with engine.begin() as conn:
        after = set(inspect(conn).get_table_names())
        columns_added = _add_missing_columns(conn)
        applied = _applied_step_names(conn)
        steps_applied = []
        for step in SCHEMA_STEPS:
            if step.name in applied:
                continue
            step.apply(conn)
            conn.execute(
                sqlalchemy.text(f"INSERT INTO {_MIGRATIONS_TABLE} (name) VALUES (:name) ON CONFLICT DO NOTHING"),
                {"name": step.name},
            )
            steps_applied.append(step.name)

    return {
        "tables_created": sorted(after - before),
        "columns_added": [f"{t}.{c}" for t, c in columns_added],
        "steps_applied": steps_applied,
    }


def schema_report(dsn: str) -> dict:
    """Read-only: what this database has versus what the models define.
    Changes nothing, so it is safe to point at production.

    `current` is True when nothing is missing and no step is pending --
    i.e. every query this codebase issues will find its table, column and
    constraint. `drift` lists differences this module will not act on by
    itself (a table or column the models no longer define, a nullability
    mismatch left behind by an added column); those are for an operator to
    resolve.
    """
    _sqlalchemy()
    from sqlalchemy import inspect, text

    from arp.storage.postgres_models import Base

    engine = get_engine(dsn)
    with engine.connect() as conn:
        inspector = inspect(conn)
        existing_tables = set(inspector.get_table_names())
        expected_tables = {t.name for t in Base.metadata.sorted_tables}
        missing_tables = sorted(expected_tables - existing_tables)
        missing_columns = [f"{t}.{c}" for t, c in _missing_columns(conn)]

        has_vector = bool(
            conn.execute(text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")).first()
        )
        applied = _applied_step_names(conn) if _MIGRATIONS_TABLE in existing_tables else set()
        pending_steps = [s.name for s in SCHEMA_STEPS if s.name not in applied]

        drift: list[str] = []
        for table_name in sorted(existing_tables & expected_tables):
            table = Base.metadata.tables[table_name]
            db_columns = {col["name"]: col for col in inspector.get_columns(table_name)}
            for column in table.columns:
                db_column = db_columns.get(column.name)
                if db_column is None:
                    continue  # already reported as missing
                if db_column["nullable"] and not column.nullable:
                    drift.append(f"{table_name}.{column.name} is nullable in the database, NOT NULL in the model")
            for name in sorted(set(db_columns) - {c.name for c in table.columns}):
                drift.append(f"{table_name}.{name} exists in the database but not in the models")

    return {
        "vector_extension": has_vector,
        "missing_tables": missing_tables,
        "missing_columns": missing_columns,
        "applied_steps": sorted(applied),
        "pending_steps": pending_steps,
        "drift": drift,
        "current": not (missing_tables or missing_columns or pending_steps or not has_vector),
    }
