"""Schema setup, evolution and verification for the opt-in Postgres store.

`Base.metadata.create_all` (what `ensure_schema` used to be, on its own)
creates *missing tables* and nothing else: it never adds a column to a
table that already exists, never drops a constraint, and leaves no record
of what a given database actually has. So a deployment that ran `arp db
init-postgres` months ago had no way to tell whether its schema matched
today's models, and found out via `UndefinedColumn` at query time. The
SQLite side had already hit this and solved it by hand, once, for one
column (`document_registry.ensure_storage_uri_column`).

This module generalizes that, deliberately without adding Alembic. Three
pieces, in the order `ensure_schema` runs them:

1. **create_all** -- new tables, unchanged behaviour.
2. **additive column reconciliation** -- for every table the models
   define, `ALTER TABLE ... ADD COLUMN` for each column the database is
   missing. This is what `ensure_storage_uri_column` did, driven off the
   models instead of a hand-written list, and it covers the overwhelmingly
   common kind of change (a new nullable/defaulted column).
3. **explicit steps** (`SCHEMA_STEPS`) -- anything reconciliation can't
   infer: dropping a constraint, backfilling, renaming. Each runs once
   per database and is recorded in `schema_migrations`, so a database
   carries a record of what has been applied. Each is also written to be
   safe if re-run.

What is deliberately *not* attempted: dropping a column or table the
models no longer define, and changing a column's type or nullability.
Those are destructive or table-rewriting, so `schema_report` reports them
as drift for an operator to resolve rather than acting on its own. That
report is what `arp db check-postgres` prints, which is the "is this
database current?" answer that didn't exist before.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING

from arp.storage.postgres import PostgresExtraNotInstalled, get_engine

if TYPE_CHECKING:
    from sqlalchemy import Connection

_MIGRATIONS_TABLE = "schema_migrations"


@dataclass(frozen=True)
class SchemaStep:
    """One recorded, run-once schema change. `apply` must be safe to call
    against a database that already satisfies it: a step is recorded only
    after it succeeds, so a crash between the DDL and the record means the
    next run calls it again."""

    name: str
    description: str
    apply: Callable[[Connection], None]


def _drop_projection_company_fks(conn: Connection) -> None:
    """Drops the `company_id -> companies.company_id` foreign keys the
    projection tables used to carry.

    They made those three projections silently insert nothing: the
    `companies` table is only populated by the dual-write portfolio store
    (so, only under ARP_PORTFOLIO_BACKEND=postgres), while the companies a
    run reports on come from the user-supplied universe file -- and the
    projections' sync hooks are best-effort, so every insert failed the
    constraint and every failure was swallowed into a log line. See the
    module docstring in postgres_models.py for the full rule.

    Finds constraints by catalog lookup rather than by name: the names
    were generated by `create_all` and a database created by an older
    SQLAlchemy may spell them differently.
    """
    from sqlalchemy import text

    rows = conn.execute(
        text(
            """
            SELECT con.conrelid::regclass::text AS table_name, con.conname AS constraint_name
            FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_class parent ON parent.oid = con.confrelid
            WHERE con.contype = 'f'
              AND parent.relname = 'legacy_companies'
              AND child.relname IN ('company_records', 'legacy_company_facts', 'engagement_issues')
            """
        )
    ).all()
    for table_name, constraint_name in rows:
        conn.execute(text(f'ALTER TABLE {table_name} DROP CONSTRAINT "{constraint_name}"'))


def _rename_legacy_table(conn: Connection, old: str, new: str, marker: str, renames: tuple[tuple[str, str], ...]) -> None:
    """Renames a legacy-shaped `old` (has column `marker`) to `new`, plus the
    pkey/index/sequence names the new same-named table would collide with."""
    from sqlalchemy import text

    cols = {r[0] for r in conn.execute(
        text("SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = :t"),
        {"t": old},
    )}
    if marker not in cols:
        return
    conn.execute(text(f"ALTER TABLE {old} RENAME TO {new}"))
    for kind, name in renames:
        legacy = name.replace(old, new, 1)
        if kind == "constraint":
            conn.execute(text(f"ALTER TABLE {new} RENAME CONSTRAINT {name} TO {legacy}"))
        else:
            conn.execute(text(f"ALTER {kind} IF EXISTS {name} RENAME TO {legacy}"))


def _rename_legacy_companies(conn: Connection) -> None:
    _rename_legacy_table(conn, "companies", "legacy_companies", "company_id", (("constraint", "companies_pkey"),))


def _rename_legacy_company_facts(conn: Connection) -> None:
    _rename_legacy_table(
        conn,
        "company_facts",
        "legacy_company_facts",
        "fact_key",
        (
            ("constraint", "company_facts_pkey"),
            ("SEQUENCE", "company_facts_id_seq"),
            ("INDEX", "ix_company_facts_current"),
            ("INDEX", "ix_company_facts_type"),
        ),
    )


def _fields_id_check(conn: Connection) -> None:
    from sqlalchemy import text

    if not conn.execute(text("SELECT 1 FROM pg_constraint WHERE conname = 'ck_fields_field_id'")).first():
        conn.execute(
            text(
                "ALTER TABLE fields ADD CONSTRAINT ck_fields_field_id"
                " CHECK (field_id ~ '^(fld_[a-z0-9]+|prov:[a-z0-9_]+:[a-z0-9_]+)$')"
            )
        )


def _create_bi_views(conn: Connection) -> None:
    from arp.bi.views import create_bi_views

    create_bi_views(conn)


def _holdings_intake(conn: Connection) -> None:
    """E77: `holdings` holds index rows beside portfolio rows. Drops the FK
    to `portfolios` (an index is no portfolio; found by catalog lookup, as in
    step 0001), lets the money columns be NULL (an index row has weights, a
    portfolio row may lack an FX rate), marks old rows as portfolio rows,
    widens the unique key by `kind`, and re-creates the BI views so they
    stay portfolio-only (step 0002 never re-runs)."""
    from sqlalchemy import text

    rows = conn.execute(
        text(
            """
            SELECT con.conname FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_class parent ON parent.oid = con.confrelid
            WHERE con.contype = 'f' AND child.relname = 'holdings' AND parent.relname = 'portfolios'
            """
        )
    ).scalars().all()
    for name in rows:
        conn.execute(text(f'ALTER TABLE holdings DROP CONSTRAINT "{name}"'))
    conn.execute(text("ALTER TABLE holdings DROP CONSTRAINT IF EXISTS uq_holdings_portfolio_security_date"))
    for column in ("quantity", "price", "market_value", "market_value_eur", "fx_rate_to_eur"):
        conn.execute(text(f"ALTER TABLE holdings ALTER COLUMN {column} DROP NOT NULL"))
    # The column was added nullable, without a default, by reconciliation.
    conn.execute(text("ALTER TABLE holdings ALTER COLUMN kind SET DEFAULT 'portfolio'"))
    conn.execute(text("UPDATE holdings SET kind = 'portfolio' WHERE kind IS NULL"))
    conn.execute(text("ALTER TABLE holdings ALTER COLUMN kind SET NOT NULL"))
    if not conn.execute(text("SELECT 1 FROM pg_constraint WHERE conname = 'uq_holdings_kind_holder_security_date'")).first():
        conn.execute(
            text(
                "ALTER TABLE holdings ADD CONSTRAINT uq_holdings_kind_holder_security_date"
                " UNIQUE (kind, portfolio_id, security_id, as_of_date)"
            )
        )
    _create_bi_views(conn)


# Run before create_all, so a legacy-shaped table does not shadow a new one of the same name.
PRE_CREATE_STEPS: tuple[SchemaStep, ...] = (
    SchemaStep("0005_rename_legacy_companies", "companies -> legacy_companies", _rename_legacy_companies),
    SchemaStep("0006_rename_legacy_company_facts", "company_facts -> legacy_company_facts", _rename_legacy_company_facts),
)

# Ordered; append new steps, never edit or reorder an existing one (a
# database that already recorded it will not run it again).
SCHEMA_STEPS: tuple[SchemaStep, ...] = (
    SchemaStep(
        name="0001_drop_projection_company_fks",
        description="Drop company_records/company_facts/engagement_issues -> companies foreign keys",
        apply=_drop_projection_company_fks,
    ),
    SchemaStep(
        name="0002_create_bi_views",
        description="Create the bi schema and the views the BI tool reads",
        apply=_create_bi_views,
    ),
    SchemaStep(
        name="0003_holdings_intake",
        description="Index holdings beside portfolio holdings: kind, nullable money columns, no FK to portfolios",
        apply=_holdings_intake,
    ),
    SchemaStep(
        name="0004_bi_published_views",
        description="Re-create the bi views so the datasets published into bi_published are readable",
        apply=_create_bi_views,
    ),
    SchemaStep(
        name="fields_id_check",
        description="CHECK on fields.field_id: fld_<id> or prov:<source>:<metric>",
        apply=_fields_id_check,
    ),
)


def _sqlalchemy():
    try:
        import sqlalchemy
    except ImportError as exc:  # pragma: no cover - exercised only without the optional extra
        raise PostgresExtraNotInstalled(exc) from exc
    return sqlalchemy


def _ensure_migrations_table(conn: Connection) -> None:
    from sqlalchemy import text

    conn.execute(
        text(
            f"CREATE TABLE IF NOT EXISTS {_MIGRATIONS_TABLE} ("
            " name TEXT PRIMARY KEY,"
            " applied_at TIMESTAMPTZ NOT NULL DEFAULT now()"
            ")"
        )
    )


def _applied_step_names(conn: Connection) -> set[str]:
    from sqlalchemy import text

    _ensure_migrations_table(conn)
    return {row[0] for row in conn.execute(text(f"SELECT name FROM {_MIGRATIONS_TABLE}")).all()}


def _missing_columns(conn: Connection) -> list[tuple[str, str]]:
    """(table, column) pairs the models define and the database lacks,
    for tables that already exist."""
    from sqlalchemy import inspect

    from arp.storage.postgres_models import Base

    inspector = inspect(conn)
    existing_tables = set(inspector.get_table_names())
    missing: list[tuple[str, str]] = []
    for table in Base.metadata.sorted_tables:
        if table.name not in existing_tables:
            continue  # create_all's job, not ours
        have = {col["name"] for col in inspector.get_columns(table.name)}
        missing.extend((table.name, column.name) for column in table.columns if column.name not in have)
    return missing


def _add_missing_columns(conn: Connection) -> list[tuple[str, str]]:
    from sqlalchemy import text

    from arp.storage.postgres_models import Base

    added = []
    for table_name, column_name in _missing_columns(conn):
        table = Base.metadata.tables[table_name]
        column = table.columns[column_name]
        ddl_type = column.type.compile(dialect=conn.dialect)
        # Added nullable regardless of the model's nullability: existing
        # rows have no value for it, so NOT NULL without a default would
        # fail outright. Tightening it afterwards is a data decision, and
        # schema_report flags the difference.
        conn.execute(text(f'ALTER TABLE {table_name} ADD COLUMN "{column_name}" {ddl_type}'))
        added.append((table_name, column_name))
    return added


def _run_steps(conn: Connection, steps: tuple[SchemaStep, ...], applied: set[str], done: list[str]) -> None:
    from sqlalchemy import text

    for step in steps:
        if step.name in applied:
            continue
        step.apply(conn)
        conn.execute(text(f"INSERT INTO {_MIGRATIONS_TABLE} (name) VALUES (:name) ON CONFLICT DO NOTHING"), {"name": step.name})
        done.append(step.name)


def ensure_schema(dsn: str) -> dict:
    """Brings a database up to what the models define, idempotently: the
    pgvector extension, any missing tables, any missing columns, then any
    unapplied step from SCHEMA_STEPS. Safe to run against a fresh
    database, one created before this module existed, or one that is
    already current (then it changes nothing). Call it from `arp db
    init-postgres`, not per request.

    Returns what it did -- `{"tables_created": [...], "columns_added":
    [...], "steps_applied": [...]}` -- so the CLI can report it instead of
    claiming success without detail.
    """
    _sqlalchemy()
    from sqlalchemy import inspect, text

    import arp.db.models  # noqa: F401  (registers the company-foundation tables on Base)
    from arp.storage.postgres_models import Base

    engine = get_engine(dsn)
    with engine.begin() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS vector"))

    steps_applied: list[str] = []
    with engine.begin() as conn:
        applied = _applied_step_names(conn)
        _run_steps(conn, PRE_CREATE_STEPS, applied, steps_applied)

    with engine.connect() as conn:
        before = set(inspect(conn).get_table_names())

    Base.metadata.create_all(engine)

    with engine.begin() as conn:
        after = set(inspect(conn).get_table_names())
        columns_added = _add_missing_columns(conn)
        _run_steps(conn, SCHEMA_STEPS, _applied_step_names(conn), steps_applied)

    return {
        "tables_created": sorted(after - before),
        "columns_added": [f"{t}.{c}" for t, c in columns_added],
        "steps_applied": steps_applied,
    }


def schema_report(dsn: str) -> dict:
    """Read-only: what this database has versus what the models define.
    Changes nothing, so it is safe to point at production.

    `current` is True when nothing is missing and no step is pending --
    i.e. every query this codebase issues will find its table, column and
    constraint. `drift` lists differences this module will not act on by
    itself (a table or column the models no longer define, a nullability
    mismatch left behind by an added column); those are for an operator to
    resolve.
    """
    _sqlalchemy()
    from sqlalchemy import inspect, text

    import arp.db.models  # noqa: F401
    from arp.storage.postgres_models import Base

    engine = get_engine(dsn)
    with engine.connect() as conn:
        inspector = inspect(conn)
        existing_tables = set(inspector.get_table_names())
        expected_tables = {t.name for t in Base.metadata.sorted_tables}
        missing_tables = sorted(expected_tables - existing_tables)
        missing_columns = [f"{t}.{c}" for t, c in _missing_columns(conn)]

        has_vector = bool(
            conn.execute(text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")).first()
        )
        applied = _applied_step_names(conn) if _MIGRATIONS_TABLE in existing_tables else set()
        pending_steps = [s.name for s in (*PRE_CREATE_STEPS, *SCHEMA_STEPS) if s.name not in applied]

        drift: list[str] = []
        for table_name in sorted(existing_tables & expected_tables):
            table = Base.metadata.tables[table_name]
            db_columns = {col["name"]: col for col in inspector.get_columns(table_name)}
            for column in table.columns:
                db_column = db_columns.get(column.name)
                if db_column is None:
                    continue  # already reported as missing
                if db_column["nullable"] and not column.nullable:
                    drift.append(f"{table_name}.{column.name} is nullable in the database, NOT NULL in the model")
            for name in sorted(set(db_columns) - {c.name for c in table.columns}):
                drift.append(f"{table_name}.{name} exists in the database but not in the models")

    return {
        "vector_extension": has_vector,
        "missing_tables": missing_tables,
        "missing_columns": missing_columns,
        "applied_steps": sorted(applied),
        "pending_steps": pending_steps,
        "drift": drift,
        "current": not (missing_tables or missing_columns or pending_steps or not has_vector),
    }
