from __future__ import annotations

from pydantic import BaseModel, Field

from arp.llm.base import LLMClient, LLMUsage
from arp.schemas.revenue_exposure import ActivityCatalogueMapping, RevenueCapexMetric
from arp.schemas.thematic import ThemeDefinition

_MAX_LABELS_PER_CALL = 2000

_SYSTEM_PROMPT = """\
You map a thematic investment activity to the labels of a company revenue/\
capex data catalogue, identifying which catalogue categories represent \
revenue or capital expenditure generated by this activity.

Select only labels that are a direct match for the activity as described \
-- the catalogue category's own name/description must plausibly BE this \
activity, not just be adjacent to or a customer/supplier of it. If nothing \
in the list is a good match, return an empty list rather than picking the \
closest-sounding one. Give a one-sentence rationale explaining the match, \
grounded in the activity's own in-scope description."""


class _LabelSelection(BaseModel):
    matched_labels: list[str] = Field(default_factory=list)
    rationale: str = ""


async def suggest_catalogue_mapping(
    theme: ThemeDefinition, labels_by_metric: dict[RevenueCapexMetric, list[str]], llm: LLMClient
) -> tuple[list[ActivityCatalogueMapping], LLMUsage]:
    """Proposes, for every (activity, metric) pair, which catalogue labels
    represent that activity's revenue/capex -- one structured call per
    pair against the metric's closed label list, mirroring
    `standards_mapping/gics.py::classify_gics`'s closed-list-with-rationale
    pattern. A reviewable draft only: the caller is expected to edit/
    confirm this before it's used in a run, never auto-applied.
    """
    mappings: list[ActivityCatalogueMapping] = []
    total_usage = LLMUsage()

    for activity in theme.activities:
        for metric, labels in labels_by_metric.items():
            if not labels:
                continue
            capped = labels[:_MAX_LABELS_PER_CALL]
            prompt = (
                f"Activity: {activity.name}\n"
                f"In scope: {activity.in_scope_description}\n"
                f"Out of scope: {activity.out_of_scope_description}\n"
                f"Metric: {metric}\n\n"
                f"Available catalogue labels:\n" + "\n".join(capped)
            )
            draft, usage = await llm.complete_structured(system=_SYSTEM_PROMPT, prompt=prompt, output_model=_LabelSelection)
            total_usage = LLMUsage(
                input_tokens=total_usage.input_tokens + usage.input_tokens,
                output_tokens=total_usage.output_tokens + usage.output_tokens,
            )
            valid_labels = {label for label in draft.matched_labels if label in capped}
            if valid_labels:
                mappings.append(
                    ActivityCatalogueMapping(activity_id=activity.activity_id, metric=metric, matched_labels=sorted(valid_labels), rationale=draft.rationale)
                )

    return mappings, total_usage
