"""Stage 8: the per-client stewardship report, from house truth plus the
client's own policies, as data (for the page) and as a PowerPoint deck.

Every figure is labelled with where it comes from: company, meeting and tier
data are the synthetic sample until real feeds exist; engagements, escalation
decisions and policy decisions are live. The deck is rendered by the existing
deterministic deck builder (`arp.reporting.deck_builder`), so it picks up the
house deck design; no text is generated by a model.
"""

from __future__ import annotations

from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

from arp.reporting.deck_builder import build_deck
from arp.schemas.engagement import EngagementRecord
from arp.schemas.reporting import (
    ChartSpec,
    ChartType,
    ColumnKind,
    ContentItem,
    DatasetColumn,
    LayoutInstructions,
    QuantitativeDataset,
    ReportPlan,
    ReportSection,
    SectionLayoutHint,
    TableSpec,
)
from arp.stewardship import escalation
from arp.stewardship.backtest import backtest
from arp.stewardship.policies import PolicyStore
from arp.stewardship.policy_review import decide, review
from arp.stewardship.process import client_escalations, client_store, current_tiers, escalation_contexts, load_sample
from arp.stewardship.tiers import TIER_LABELS, TIERS

VOTES = ["for", "against", "abstain", "case_by_case"]


def _w(s: str | None) -> str:
    return (s or "").replace("_", " ")


def client_report(root: Path, stream: dict, records: list[EngagementRecord], sla_days: int) -> dict:
    sample = load_sample()
    house_store = PolicyStore(root)
    house_policy = house_store.active("house_voting")
    names = {i["issuer_id"]: i["name"] for i in sample["issuers"]} | {r.company_id: r.name for r in records}

    tiers = Counter(current_tiers(root, sample, records).values())
    ctxs = escalation_contexts(root, sample, records, sla_days)
    house = escalation.evaluate(house_store.active("escalation_rules"), ctxs)
    engagements = client_escalations(root, stream["stream_id"], ctxs, house)
    esc_version = client_store(root, stream["stream_id"]).active_version("escalation_rules")

    result = decide(review(stream["client_policy"], house_policy), stream["decisions"], strict=False)
    differences = [r for r in result["register"] if "assessment" in r]
    decided = [r for r in differences if r["decision"]]
    built = stream.get("built_policy")
    votes = backtest(house_policy, built, sample) if built else None
    exceptions = stream.get("exception_decisions", [])

    summary = [
        f"Vehicle: {stream['client_policy'].get('mandate', {}).get('vehicle_type', 'not set')}.",
        (
            f"Voting policy: custom policy built, {sum(p['origin'] == 'client' for p in built['positions'])} client positions."
            if built
            else f"Voting policy: in review, {len(decided)} of {len(differences)} differences decided."
        ),
        f"Escalation rules: {'version ' + str(esc_version) if esc_version else 'same as the house'}; "
        f"{sum(r['higher'] for r in engagements)} of {len(engagements)} open engagements above the house step.",
        f"Client escalations decided by the house: {sum(e['decision'] == 'adopt' for e in exceptions)} adopted, "
        f"{sum(e['decision'] == 'decline' for e in exceptions)} kept at the house step.",
    ]
    if votes:
        summary.append(f"Expected votes: {votes['changed']} of {votes['resolutions']} resolutions differ from the house.")

    return {
        "client": stream["name"],
        "stream_id": stream["stream_id"],
        "as_of": datetime.now(UTC).date().isoformat(),
        "summary": summary,
        "tiers": [{"tier": TIER_LABELS[t], "companies": tiers.get(t, 0)} for t in TIERS],
        "votes": [
            {"vote": _w(v), "house": votes["base_votes"].get(v, 0), "client": votes["other_votes"].get(v, 0)} for v in VOTES
        ]
        if votes
        else [],
        "engagements": [
            {
                "company": r["company"],
                "theme": _w(r["theme"]),
                "data": r["source"],
                "step now": _w(r["current"]),
                "house step": _w(r["house_recommended"]),
                "client step": _w(r["recommended"]),
                "above the house": "yes" if r["higher"] else "no",
            }
            for r in engagements
        ],
        "exceptions": [
            {
                "company": names.get(e["company_id"], e["company_id"]),
                "theme": _w(e["theme"]),
                "house step": _w(e["house_step"]),
                "client step": _w(e["client_step"]),
                "decision": "adopted" if e["decision"] == "adopt" else "kept the house step",
                "decided by": e["decided_by"],
                "date": e["decided_at"][:10],
            }
            for e in exceptions
        ],
        "policy_decisions": [
            {"issue": r["title"] or r["issue_id"], "difference": _w(r["kind"]), "decision": _w(r["decision"]["decision"])}
            for r in decided
        ],
        "notes": [
            "Company data, holdings, tiers, meetings and expected votes: synthetic sample (fictional companies).",
            "Engagements marked 'live', escalation decisions and policy decisions: the house's records.",
            "Expected votes are what the policies imply; the tool does not cast votes.",
        ],
    }


def _dataset(name: str, rows: list[dict], numeric: set[str] = frozenset()) -> QuantitativeDataset:
    cols = list(rows[0]) if rows else []
    return QuantitativeDataset(
        dataset_id=name,
        name=name,
        columns=[DatasetColumn(name=c, kind=ColumnKind.NUMBER if c in numeric else ColumnKind.CATEGORY) for c in cols],
        rows=rows,
    )


def build_pptx(report: dict, out_path: Path) -> Path:
    def text(*lines: str) -> list[ContentItem]:
        return [ContentItem(text=t) for t in lines]

    datasets = [
        _dataset("tiers", report["tiers"], {"companies"}),
        _dataset("votes", report["votes"], {"house", "client"}),
        _dataset("engagements", report["engagements"]),
        _dataset("exceptions", report["exceptions"]),
        _dataset("policy_decisions", report["policy_decisions"]),
    ]
    sections = [
        ReportSection(
            heading="The programme at a glance", layout_hint=SectionLayoutHint.TEXT_ONLY, narrative=text(*report["summary"])
        ),
        ReportSection(
            heading="Coverage tiers",
            narrative=text("How deeply the house engages each company it holds (sample)."),
            chart=ChartSpec(dataset_id="tiers", chart_type=ChartType.BAR, category_column="tier", value_columns=["companies"]),
        ),
    ]
    if report["votes"]:
        sections.append(
            ReportSection(
                heading="Expected votes: client policy against the house",
                narrative=text("Votes the policies imply on the sample meetings."),
                chart=ChartSpec(
                    dataset_id="votes", chart_type=ChartType.COLUMN, category_column="vote", value_columns=["house", "client"]
                ),
            )
        )
    sections.append(
        ReportSection(
            heading="Engagements and escalation",
            layout_hint=SectionLayoutHint.CHART_FOCUS,
            narrative=text("House step and the client's step per open engagement."),
            table=TableSpec(dataset_id="engagements", max_rows=12),
        )
        if report["engagements"]
        else ReportSection(heading="Engagements and escalation", narrative=text("No open engagements."))
    )
    sections.append(
        ReportSection(
            heading="Client escalations decided by the house",
            layout_hint=SectionLayoutHint.CHART_FOCUS,
            table=TableSpec(dataset_id="exceptions", max_rows=12),
        )
        if report["exceptions"]
        else ReportSection(heading="Client escalations decided by the house", narrative=text("None so far."))
    )
    if report["policy_decisions"]:
        sections.append(
            ReportSection(
                heading="Voting policy decisions",
                layout_hint=SectionLayoutHint.CHART_FOCUS,
                table=TableSpec(dataset_id="policy_decisions", max_rows=14),
                appendix=True,
            )
        )
    sections.append(
        ReportSection(
            heading="Data sources", layout_hint=SectionLayoutHint.TEXT_ONLY, narrative=text(*report["notes"]), appendix=True
        )
    )
    plan = ReportPlan(title=f"{report['client']}: stewardship report", subtitle=f"As of {report['as_of']}", sections=sections)
    return build_deck(plan, datasets, LayoutInstructions(include_appendix=True), None, out_path)
